### ISSUE TITLE
小程序中 如何适配 IPhone X 系列

### ISSUE THREAD

**Issue by JslinSir** [JslinSir/my-blog#1]
[苹果 websites 设计规范](https://webkit.org/blog/7929/designing-websites-for-iphone-x/?hmsr=funteas.com&utm_medium=funteas.com&utm_source=funteas.com)
### 安全区示意图
 
<img width="957" alt="329554c7855a238a" src="https://user-images.githubusercontent.com/30678791/165018571-6a692acf-010d-48fd-8e5f-0a17b5050cdf.png">

### 小程序中适配
```css
padding-bottom: constant( safe-area-inset-bottom); /* 兼容 iOS < 11.2 */
padding-bottom: env( safe-area-inset-bottom); /* 兼容 iOS >= 11.2 */
```
`注意：env() 跟 constant() 需要同时存在，而且顺序不能换`
###  使用 @supports 隔离兼容样式
```css
@supports (bottom: constant(safe-area-inset-bottom)) or (bottom: env(safe-area-inset-bottom)) {
.iphone-x {
      padding-bottom: constant(safe-area-inset-bottom);
      padding-bottom: env(safe-area-inset-bottom);
   }
}

```
### 效果展示
<img width="353" alt="WeChatefd0056ba6fd0feec80568f20a12a18c" src="https://user-images.githubusercontent.com/30678791/165021723-0357a508-94a2-4c6e-9747-83161b66fa4e.png">

###  同样也支持  calc 写法
非x 系列设备，距离底部距离
```css
@supports (bottom: constant(safe-area-inset-bottom)) or (bottom: env(safe-area-inset-bottom)) {
.iphone-x {
      padding-bottom: calc(10rpx + constant(safe-area-inset-bottom));
      padding-bottom: calc(10rpx  + env(safe-area-inset-bottom));
   }
}
```

**Comment by JslinSir** [comment]
### H5 适配 IPhone X 系列
* 在 meta 标签中增加 viewport-fit=cover
```html
 <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,viewport-fit=cover" /> 
```
*  设置body 安全区
``` css
 body {
  /* 适配齐刘海*/
  padding-top: constant(safe-area-inset-top);  
  padding-top: env(safe-area-inset-top);  
  /* 适配底部黑条*/
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
}
```
