### ISSUE TITLE
H5 css 样式重置

### ISSUE THREAD

**Issue by JslinSir** [JslinSir/my-blog#18]
# 去除浏览器默认的样式

## 一些样式重置  
```css
*,
:after,
:before {
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0)
}

blockquote,
body,
dd,
div,
dl,
dt,
fieldset,
form,
h1,
h2,
h3,
h4,
h5,
h6,
input,
legend,
li,
ol,
p,
td,
textarea,
th,
ul {
    margin: 0;
    padding: 0
}

table {
    border-collapse: collapse;
    border-spacing: 0
}

fieldset,
img {
    border: 0
}

li {
    list-style: none
}

caption,
th {
    text-align: left
}

q:after,
q:before {
    content: ""
}

input:password {
    ime-mode: disabled
}

:focus {
    outline: none
}

body,
html {
    min-height: 100%
}

body {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none
}

a,
img {
    -webkit-touch-callout: none
}
```
